### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by zdodson21** [htmlplusplus/code-block#1]
- [x] Finish copy button functionality
- [x] Light and dark mode support, light mode adds gray border, dark mode adds white border (make variable `--theme-border-color`)
- [x] Modify README.md

**Comment by zdodson21** [comment]
Future features:

- [ ] CSS Variables for complete control over border color
